[server]
headless = true
enableCORS = false
port = 8501
[theme]
primaryColor = "#2E8B57"  # change to any hex color you like
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"

